version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.7.0
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get install -y libpng-dev
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist/*
